name: bit_array
description: >
  A bit array (also known as BitMap, BitSet, BitString, or BitVector)
  is an array data structure that compactly stores bits.
version: 2.2.0
homepage: https://github.com/isoos/bit_array

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
